# Generated by Django 2.1.1 on 2019-03-17 09:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20190317_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='richtext',
            name='content_images',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
