# Generated by Django 2.1.1 on 2019-03-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_richtext_content_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richtext',
            name='content',
        ),
    ]
