# Generated by Django 2.1.1 on 2019-03-17 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_remove_richtext_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='richtext',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
