# Generated by Django 2.1.1 on 2019-03-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_richtext_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richtext',
            name='content_link',
        ),
    ]
